### ISSUE TITLE
feat: add support to decode base64 string to PEM object

### ISSUE THREAD

**Issue by alefhsousa** [jcreekmore/pem-rs#57]
Hey @jcreekmore, in my use case here, I had a couple of strings in base64 that represent many poems, and we encode these poems as base64 to keep them easier to store in external secrets, environment variables, etc.

So, I need to duplicate a couple of lines of code to orchestrate the String, decode it to vec[u8], and start managing this data.

My suggestion is to add a new type to this library that makes this possible, for example:

```rust 
pub struct PemB64 {
    pem_b64: String,
}

impl PemB64 {
     pub fn pem(&self) -> Result<Pem> {
        let key_pem: Result<&str, PemError> = base64::engine::general_purpose::STANDARD
            .decode(&self.pem_b64)
            .map_err(PemError::InvalidData)
            .and_then(|item| std::str::from_utf8(&item).map_err(PemError::NotUtf8));
        
          parse(pem_string)
     }
}
```

Do you think this makes sense? I'll be able to open a PR to add this feature

**Comment by jcreekmore** [comment]
I have done this exact same thing in the past for different applications (not necessarily using this crate, but in other ecosystems), so I know exactly what you are talking about here.

However, I think adding it to this crate is a bit overkill. You are talking about replacing a call to a version of `base64::engine::general_purpose::STANDAR::decode` (for one of the engines) and taking that result, which is a `Vec<u8>`, and passing that to `parse` (which takes anything that is `AsRef<[u8]>`). So, replacing two lines of code with one line of code. 

By introducing a separate type (or even a helper function here), you are not really saving much. However, those same two lines COULD be implemented with `base64::engine::general_purpose::URL_SAFE::decode` or a custom engine that the end user needs, or extracting into a user-defined buffer (instead of allocating for it) OR the two lines could be calling `parse_many` to extract multiple PEM objects from the buffer instead of just `parse`. 

I think carrying a helper for your use-case in this crate is really outside the scope and it probably makes more sense to carry a small helper function in your own codebase.
